CREATE TABLE IF NOT EXISTS vets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT
);
CREATE INDEX ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
  vet_id       INT NOT NULL REFERENCES vets (id),
  specialty_id INT NOT NULL REFERENCES specialties (id),
  UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON types (name);

CREATE TABLE IF NOT EXISTS owners (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  address    TEXT,
  city       TEXT,
  telephone  TEXT
);
CREATE INDEX ON owners (last_name);

CREATE TABLE IF NOT EXISTS pets (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT,
  birth_date DATE,
  type_id    INT NOT NULL REFERENCES types (id),
  owner_id   INT REFERENCES owners (id)
);
CREATE INDEX ON pets (name);
CREATE INDEX ON pets (owner_id);
CREATE UNIQUE INDEX unique_owner_pet_name ON pets (owner_id, LOWER(name));

CREATE TABLE IF NOT EXISTS visits (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INT REFERENCES pets (id),
  visit_date  DATE,
  description TEXT
);
CREATE INDEX ON visits (pet_id);

CREATE TABLE IF NOT EXISTS visit_rate_limits (
  pet_id INT PRIMARY KEY REFERENCES pets (id),
  window_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
  attempt_count INT NOT NULL
);

CREATE TABLE IF NOT EXISTS reminders (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id         INT NOT NULL REFERENCES visits (id),
  owner_id         INT NOT NULL REFERENCES owners (id),
  pet_name         TEXT NOT NULL,
  visit_date       DATE NOT NULL,
  destination_hint TEXT NOT NULL,
  status           TEXT NOT NULL,
  attempt_count    INT NOT NULL,
  created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
  last_attempt_at  TIMESTAMP WITH TIME ZONE,
  accepted_at      TIMESTAMP WITH TIME ZONE,
  last_error       TEXT,
  CONSTRAINT uk_reminders_visit UNIQUE (visit_id)
);
CREATE INDEX IF NOT EXISTS reminders_status ON reminders (status);
